version: '3'
services:
   zookeeper:
    image: wurstmeister/zookeeper
    container_name: "zk"
    ports:
      - "2181:2181"
   kafka:
    image: wurstmeister/kafka
    container_name: "kafka"
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_CREATE_TOPICS: "workunits:1:1"
      KAFKA_ENABLE_AUTO_COMMIT: "false"
    links:
    - zookeeper:zk
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
   mongodb:
    image: mongo:3.0.4
    ports:
      - "27017:27017"
    command: mongod --smallfiles